### ISSUE TITLE
GutHub Desktop - Syncing with github.com

### ISSUE THREAD

**Issue by CSBCounsel** [KCLegalHackers/CodingForLawyers#7]
I installed the desktop client, but I can't figure out how to sync it with my online account. I logged in to my account on the desktop client, but that's all I can do.

It almost looks like I can't sync them. I can clone or import projects, but I an't truly sync them. 

Anyone know if they are supposed to sync? @bryangw1 @zmon ??

Thanks!

**Comment by JwhiteheadMO** [comment]
I was just doing that myself.  There's probably a more direct way, but once
you are logged in, you can go to the online repository and Clone or
Download -> Open in Desktop.   You'll be prompted to add it to your desktop
client.

Then, you can edit the local files with whatever text editor you like.
 (Repository -> Open in Finder).  When your edits are done, sync back to
the hub with the client.  It automatically figures out which files have
been changed locally...

**Comment by CSBCounsel** [comment]
@JwhiteheadMO - that's what I was thinking. So unfortunately, it doesn't automatically sync. That's too bad. I was hoping it'd be like my email client. No matter where I log in (desktop, phone, browser, etc.) it is always synced.

**Comment by dwmcqueen** [comment]
That is part of the nature of github's underpinning, git.  You don't want it to auto-sync since you may have local work that would get overwritten (such as were two of us are working on the same file).  I think git's advantage over prior systems was that it distributed out the work so one person didn't, in effect, lock a file and prevent anyone else from working on it.

**Comment by CSBCounsel** [comment]
Thanks Duncan. Also, closing out this issue since we now know this can't be done. :)
